#!/usr/bin/env ruby

require 'bundler'
require 'tty/cli'

Signal.trap("INT") do
  warn("\n#{caller.join("\n")}: interrupted")
  exit(1)
end

begin
  TTY::CLI.start
rescue TTY::CLI::Error => err
  puts "ERROR: #{err.message}"
  exit 1 #err.status
end
